version: '3'

services:
  app:
    build: .
    container_name: micro-catalog-app
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - micro-catalog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: micro-catalog-elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./docker/elasticsearch/data:/usr/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - micro-catalog

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: micro-catalog-kibana
    ports:
      - 5601:5601
    networks:
      - micro-catalog

networks:
  micro-catalog:
    driver: bridge
